spring:
  alicloud:
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      appcode: 762689c204704b2eb982e5647936edec
      sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
      template-id: 908e94ccf08b4476ba6c876d13f084ad
  # rabbitMQ相关信息
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
